# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.5
  publish_frequency: 0.5
  resolution: 0.05
  static_map: true
  width: 10.0
  height: 10.0
